alias: EspGps<MQTT_CLIENT_ID>MQTTData
trigger:
  - platform: mqtt
    topic: <MQTT_TOPIC>/<MQTT_CLIENT_ID>/data
action:
  - service: device_tracker.see
    data:
      dev_id: <MQTT_CLIENT_ID>
      gps:
        - "{{ trigger.payload_json.loc_lat }}"
        - "{{ trigger.payload_json.loc_lng }}"
      attributes:
        gps_accuracy: "{{ trigger.payload_json.loc_confidence }}"
        gps_mode: "{{ ['Invalid', 'GPS', 'GSM'][trigger.payload_json.loc_type] }}"
        last_seen: "{{ trigger.payload_json.timestamp | timestamp_local() }}"
        battery: "{{ trigger.payload_json.bat_vlt / 1000 }}v"
        battery_state: "{{ ['Charging', 'Discharging', 'Low', 'Critical'][trigger.payload_json.bat_state] }}"
