#region Devices
[env:c3]
extends = esp32, debug
board = wifiduino32c3
board_build.f_cpu = 80000000L

[env:s3]
extends = esp32, debug
board = lolin_s3

; https://www.reddit.com/r/esp32/comments/1ananz5/esp32_c6_in_platformio_for_arduino_framework/
; https://github.com/platformio/platform-espressif32/issues/1225#issuecomment-1977825930
; https://github.com/TobiKr/T-Display-S3-ModernBasicTemplate/blob/main/platformio.ini
; Run on Linux/WSL
[env:c6]
extends = esp32, debug
platform = https://github.com/pioarduino/platform-espressif32.git
platform_packages =
	; platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.1.1
	; platformio/framework-arduinoespressif32-libs @ https://github.com/espressif/esp32-arduino-libs.git#idf-release/v5.1
board = esp32-c6-devkitc-1
; framework = arduino
; build_flags =
; 	-fexceptions
; 	-DESP32_STAGE
; 	-DESP_IDF_VERSION_MAJOR=5
; 	-DLIBRARIES_NO_LOG=1
; 	-DDISABLE_SC16IS752_SPI
; 	-DCONFIG_PM_ENABLE
; 	-DCONFIG_LWIP_L2_TO_L3_COPY
; 	-DCONFIG_FREERTOS_USE_TICKLESS_IDLE=1
; 	-DCONFIG_FREERTOS_IDLE_TIME_BEFORE_SLEEP=3
; 	-DNEOPIXEL_ESP32_RMT_DEFAULT
; 	-DCRON_USE_LOCAL_TIME
; 	-I$PROJECT_DIR/src/include
; 	-include "sdkconfig.h"

[env:esp32_dev]
extends = esp32, debug
board = esp32dev
board_build.f_cpu = 80000000L
; board_build.f_cpu = 160000000L
#endregion

#region Platform settings
[esp32]
extends = globals
platform = espressif32
framework = arduino
monitor_speed = 115200

[esp32_debug]
extends = esp32, debug
debug_tool = esp-builtin
debug_server = 
	C:/Users/ReadieFur/.platformio/packages/tool-openocd-esp32/bin/openocd
	-f
#endregion

#region Build settings
[globals]
framework = arduino
build_type = release
build_flags =
	-std=c++17
	-std=gnu++17
	-Wno-unknown-pragmas ;https://stackoverflow.com/questions/12894454/how-to-remove-gcc-warning-on-pragma-region
	-Wno-format ;Caused by a format error within esp_log.h
	-Wno-missing-field-initializers
	-Wno-unused-variable
	-Wno-comment
	-fno-exceptions
	; -DconfigUSE_TRACE_FACILITY=1
	; -DconfigGENERATE_RUN_TIME_STATS=1
	; -DconfigUSE_STATS_FORMATTING_FUNCTIONS=1
build_unflags =
	-std=gnu++11
	-fexceptions
	-fno-rtti
	-Wunknown-pragmas
monitor_raw = yes
; monitor_filters = 
; 	colorize
; 	debug
; 	esp32_exception_decoder
; 	time
lib_deps =
	mikalhart/TinyGPSPlus@^1.1.0
	arduino-libraries/ArduinoHttpClient@^0.6.1
	adafruit/Adafruit MPU6050@^2.2.6
	bblanchon/ArduinoJson@^7.2.0
	knolleary/PubSubClient@^2.8

[release]
extends = globals
build_flags =
	${globals.build_flags}
	-DCORE_DEBUG_LEVEL=1

[debug]
extends = globals
build_type = debug
; debug_test = *
build_unflags =
	${globals.build_unflags}
build_flags =
	${globals.build_flags}
	-DCORE_DEBUG_LEVEL=5 ;https://community.platformio.org/t/how-to-set-up-log-level-to-be-able-to-debug-the-esp32/8278/2
	-D DEBUG
	;https://github.com/espressif/openocd-esp32/issues/246
	-O0
	-g
	-D CONFIG_COMPILER_OPTIMIZATION_NONE
lib_ldf_mode = deep ;https://github.com/me-no-dev/ESPAsyncWebServer/issues/520
lib_extra_dirs = components
test_framework = unity
test_speed = 115200
debug_init_break = break setup
#endregion
